backend:
  - any:
    - 'api/**/*'

smart-contract:
  - any:
    - 'web3/**/*'

frontend:
  - any:
    - 'web/**/*'

documentation:
  - any:
    - 'docs/**/*'
    - 'README.md'

github-actions:
  - any:
    - '.github/**/*'
